// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDaQ_H_JZC8-akF25X7t69XxeR-nar6k',
    appId: '1:244100597067:web:15eb8ad33c8220505654ce',
    messagingSenderId: '244100597067',
    projectId: 'sicv-flutter',
    authDomain: 'sicv-flutter.firebaseapp.com',
    storageBucket: 'sicv-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTVloqvvXW7KRxJMUUpvCdxHryMYz1ktg',
    appId: '1:244100597067:android:db31874ca90475005654ce',
    messagingSenderId: '244100597067',
    projectId: 'sicv-flutter',
    storageBucket: 'sicv-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqueH2l-79Nc52VK8-9OO0LunQ6pPeMzM',
    appId: '1:244100597067:ios:9b34a534fb1f19ec5654ce',
    messagingSenderId: '244100597067',
    projectId: 'sicv-flutter',
    storageBucket: 'sicv-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sicvFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqueH2l-79Nc52VK8-9OO0LunQ6pPeMzM',
    appId: '1:244100597067:ios:9b34a534fb1f19ec5654ce',
    messagingSenderId: '244100597067',
    projectId: 'sicv-flutter',
    storageBucket: 'sicv-flutter.firebasestorage.app',
    iosBundleId: 'com.example.sicvFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtDaQ_H_JZC8-akF25X7t69XxeR-nar6k',
    appId: '1:244100597067:web:171fe2826b4ef8165654ce',
    messagingSenderId: '244100597067',
    projectId: 'sicv-flutter',
    authDomain: 'sicv-flutter.firebaseapp.com',
    storageBucket: 'sicv-flutter.firebasestorage.app',
  );
}
